version: "0.0.1"
services:
  consul:
    image: "consul:1.13.1"
    restart: always
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    volumes:
      - ./docker_volume/consul/data:/consul/data
    environment:
      - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}'
    command: "agent -server -bind=0.0.0.0 -client=0.0.0.0 -ui -bootstrap-expect=1 -node=agent-0 -enable-script-checks=true"
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
        max-file: 3
  mysql:
    image: "mysql:8.0.30"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./docker_volume/mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/:ro
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
        max-file: 3
  redis:
    image: "redis:7.0.4-alpine"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./docker_volume/redis/data:/data
      - ./redis/redis.conf:/redis.conf:ro
    command: "redis-server /redis.conf"
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
        max-file: 3
  nginx:
    image: "nginx:1.23.1-alpine"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/docker_volume/cert:/etc/nginx/cert:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
        max-file: 3
